apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: # it defines the behaviour of the deployment
   replica: 2
  selector:
    matchLabels:
      app: web
  template: # it defines the pod definition
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-conatiner
        image: manjunadha1993/sre-test-image:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
           request:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3015
